apiVersion: batch/v1
kind: CronJob
metadata:
  name: quarterly-business-report-automation
  namespace: default
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'quarterly_business_report_automation'
            vault.hashicorp.com/agent-inject-secret-opsgenie-quarterly_business_report_automation: 'secret/opsgenie/quarterly_business_report_automation'
            vault.hashicorp.com/agent-inject-template-opsgenie-quarterly_business_report_automation: |
              {{- with secret "secret/opsgenie/quarterly_business_report_automation" -}}
                export OPSGENIE_API_KEY="{{ .Data.data.api_key }}"
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-prtg: 'secret/prtg'
            vault.hashicorp.com/agent-inject-template-prtg: |
              {{- with secret "secret/prtg" -}}
                export PRTG_DEFAULT_INSTANCE_URL="{{ .Data.data.instance_url }}"
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-prtg-quarterly_business_report_automation: 'secret/prtg/quarterly_business_report_automation'
            vault.hashicorp.com/agent-inject-template-prtg-quarterly_business_report_automation: |
              {{- with secret "secret/prtg/quarterly_business_report_automation" -}}
                export PRTG_DEFAULT_API_KEY="{{ .Data.data.api_key }}"
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-servicenow: 'secret/servicenow'
            vault.hashicorp.com/agent-inject-template-servicenow: |
              {{- with secret "secret/servicenow" -}}
                export SERVICENOW_INSTANCE_NAME="{{ .Data.data.instance_name }}"
                export SERVICENOW_USERNAME="{{ .Data.data.anthony_username }}"
                export SERVICENOW_PASSWORD="{{ .Data.data.anthony_password }}"
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-smartsheet-quarterly_business_report_automation: 'secret/smartsheet/quarterly_business_report_automation'
            vault.hashicorp.com/agent-inject-template-smartsheet-quarterly_business_report_automation: |
              {{- with secret "secret/smartsheet/quarterly_business_report_automation" -}}
                export SMARTSHEET_API_KEY="{{ .Data.data.api_key }}"
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-quarterly_business_report_automation: 'secret/quarterly_business_report_automation'
            vault.hashicorp.com/agent-inject-template-quarterly_business_report_automation: |
              {{- with secret "secret/quarterly_business_report_automation" -}}
                export CUSTOMER_CONFIGS="{{ .Data.data.customer_configs }}"
              {{- end }}
            vault.hashicorp.com/ca-cert: /run/secrets/kubernetes.io/serviceaccount/ca.crt
        spec:
          containers:
            - image: registry.quokka.ninja/ccfs/quarterly-business-report-automation:0.0.1
              name: quarterly-business-report-automation
              args: ['/bin/bash', '-c', 'source /vault/secrets/opsgenie-quarterly_business_report_automation && source /vault/secrets/prtg && source /vault/secrets/prtg-quarterly_business_report_automation && source /vault/secrets/servicenow && source /vault/secrets/smartsheet-quarterly_business_report_automation && source /vault/secrets/quarterly_business_report_automation && python ./src/quarterly_business_report_automation.py']
          restartPolicy: Never
          serviceAccountName: quarterly-business-report-automation
      backoffLimit: 3
  schedule: 0 9 * * *