apiVersion: batch/v1
kind: CronJob
metadata:
  name: quarterly-business-report-automation
  namespace: default
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'quarterly_business_report_automation'
            vault.hashicorp.com/agent-inject-secret-opsgenie-qbr_auto: 'secret/opsgenie/qbr_auto'
            vault.hashicorp.com/agent-inject-template-opsgenie-qbr_auto: |
              {{- with secret "secret/opsgenie/qbr_auto" -}}
                export OPSGENIE_API_KEY="{{ .Data.data.api_key }}"
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-prtg: 'secret/prtg'
            vault.hashicorp.com/agent-inject-template-prtg: |
              {{- with secret "secret/prtg" -}}
                export PRTG_DEFAULT_INSTANCE_URL="{{ .Data.data.instance_url }}"
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-prtg-qbr_auto: 'secret/prtg/qbr_auto'
            vault.hashicorp.com/agent-inject-template-prtg-qbr_auto: |
              {{- with secret "secret/prtg/qbr_auto" -}}
                export PRTG_DEFAULT_API_KEY="{{ .Data.data.api_key }}"
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-servicenow: 'secret/servicenow'
            vault.hashicorp.com/agent-inject-template-servicenow: |
              {{- with secret "secret/servicenow" -}}
                export SERVICENOW_INSTANCE_NAME="{{ .Data.data.instance_name }}"
                export SERVICENOW_USERNAME="{{ .Data.data.anthony_username }}"
                export SERVICENOW_PASSWORD="{{ .Data.data.anthony_password }}"
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-smartsheet-qbr_auto: 'secret/smartsheet/qbr_auto'
            vault.hashicorp.com/agent-inject-template-smartsheet-qbr_auto: |
              {{- with secret "secret/smartsheet/qbr_auto" -}}
                export SMARTSHEET_API_KEY="{{ .Data.data.api_key }}"
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-qbr_auto: 'secret/qbr_auto'
            vault.hashicorp.com/agent-inject-template-qbr_auto: |
              "{{- with secret "secret/qbr_auto" -}}
              {{ .Data.data.customer_configs | toUnescapedJSON }}
              {{- end }}"
            vault.hashicorp.com/secret-volume-path: /vault/secret/
            vault.hashicorp.com/agent-inject-file-qbr_auto: qbr_auto
            vault.hashicorp.com/ca-cert: /run/secrets/kubernetes.io/serviceaccount/ca.crt
        spec:
          containers:
            - image: harbor.k3s.quokka.ninja/library/quarterly-business-report-automation:0.0.16
              name: quarterly-business-report-automation
              args: ['/bin/bash', '-c', 'source /vault/secret/opsgenie-qbr_auto && source /vault/secret/prtg && source /vault/secret/prtg-qbr_auto && source /vault/secret/servicenow && source /vault/secret/smartsheet-qbr_auto && cat /vault/secret/qbr_auto > /vault/secret/qbr_auto && python ./src/quarterly_business_report_automation.py']
          restartPolicy: Never
          serviceAccountName: quarterly-business-report-automation
      backoffLimit: 3
  schedule: 0 9 * * *
